import { SubscriptionLayout } from '@/Layout/Layouts/SubscriptionLayout'
import '@/firebase'
import { setupStore } from '@/store/store'
import { getDatabase, onValue, ref } from 'firebase/database'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { Provider } from 'react-redux'
import styles from '@/PageStyle.module.scss'



const store = setupStore()

const Materials = (): JSX.Element => {
    const [courseName, setCourseName] = useState<string>('')
    const router = useRouter()
    const db = getDatabase()

    useEffect(() => {
        if(router.query.courseid){
            onValue(ref(db, `courses/${router.query.courseid}/courseName`), (data) => {
                if(data.val()){
                    setCourseName(data.val())
                }
            })
        }
    }, [router.query.courseid])
    return(
        <>
            <Head>
                <title>{courseName}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Provider store={store}>
                <SubscriptionLayout className={styles.pageWrapper}/>
            </Provider>
        </>
    )
}

export default Materials