import { SubscriptionsPage } from '@/Layout/SubscriptionsPage/SubscriptionsPage'
import '@/firebase'
import { setupStore } from '@/store/store'
import Head from 'next/head'
import { Provider } from 'react-redux'
import styles from '@/PageStyle.module.scss'



const store = setupStore()

const Subscribes = (): JSX.Element => {
    return(
        <>
            <Head>
                <title>Мои подписки</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Provider store={store}>
                <SubscriptionsPage className={styles.pageWrapper}/>
            </Provider>
        </>
    )
}

export default Subscribes