import { ProfilePage } from "@/Layout/ProfilePage/ProfilePage"
import { setupStore } from "@/store/store"
import { Provider } from "react-redux"
import '@/firebase'
import Head from "next/head"



const store = setupStore()

const Profile = (): JSX.Element => {
    return(
        <>
            <Head>
                <title>Akerke Courses</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Provider store={store}>
                <ProfilePage/>
            </Provider>
        </>
    )
}

export default Profile