import Head from 'next/head'
import { Homepage } from '@/Layout/Homepage/Homepage'
import { Provider } from 'react-redux'
import { setupStore } from '@/store/store'
import styles from '@/PageStyle.module.scss'

const store = setupStore()

export default function Home() {
    return (
        <>
            <Head>
                <title>Akerke Courses</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Provider store={store}>
                <Homepage className={styles.pageWrapper}/>
            </Provider>
        </>
    )
}
