import { CourseLayout } from '@/Layout/Layouts/CourseLayout'
import '@/firebase'
import { setupStore } from '@/store/store'
import { getDatabase, onValue, ref } from 'firebase/database'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { Provider } from 'react-redux'
import styles from '@/PageStyle.module.scss'



const store = setupStore()

const Course = (): JSX.Element => {
    const [cid, setCid] = useState<string>('')
    const [courseName, setCourseName] = useState<string>('')
    const router = useRouter()
    const db = getDatabase()

    useEffect(() => {
        if(router.query.courseid){
            setCid(`${router.query.courseid}`)
        }
    }, [router.query.courseid])

    useEffect(() => {
        if(cid){
            onValue(ref(db, `courses/${cid}/courseName`), (data) => {
                setCourseName(data.val())
            })
        }
    }, [cid])

    
    return(
        <>
            <Head>
                <title>{courseName?courseName:"Akerke Courses"}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Provider store={store}>
                <CourseLayout className={styles.pageWrapper} cid={cid}/>
            </Provider>
        </>
    )
}

export default Course