import { CoursesPage } from '@/Layout/CoursesPage/CoursesPage'
import '@/firebase'
import { setupStore } from '@/store/store'
import Head from 'next/head'
import { Provider } from 'react-redux'



const store = setupStore()

const Courses = (): JSX.Element => {
    return(
        <>
            <Head>
                <title>Akerke Courses</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Provider store={store}>
                <CoursesPage/>
            </Provider>
        </>
    )
}

export default Courses